<?php

namespace ContainerRxkstsp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X5InieAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x5InieA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x5InieA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.y27w51G.App\\Controller\\AdminController::index()', 'getAdminControllerindexService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.tEL1pRK.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.KHhLDTq.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\TaskController::index' => ['privates', '.service_locator.HTuWMbh.App\\Controller\\TaskController::index()', 'getTaskControllerindexService', true],
            'App\\Controller\\TaskController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\TaskController::new()', 'getTaskControllernewService', true],
            'App\\Controller\\TaskController::show' => ['privates', '.service_locator.kvKRcXA.App\\Controller\\TaskController::show()', 'getTaskControllershowService', true],
            'App\\Controller\\TaskController::edit' => ['privates', '.service_locator.Kt7uJgt.App\\Controller\\TaskController::edit()', 'getTaskControllereditService', true],
            'App\\Controller\\TaskController::delete' => ['privates', '.service_locator.Kt7uJgt.App\\Controller\\TaskController::delete()', 'getTaskControllerdeleteService', true],
            'App\\Controller\\TaskController::toggle' => ['privates', '.service_locator.7Be6WBa.App\\Controller\\TaskController::toggle()', 'getTaskControllertoggleService', true],
            'App\\Controller\\TaskController::list' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TaskController::list()', 'getTaskControllerlistService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.CQIMZqF.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::update' => ['privates', '.service_locator.lQAlGdR.App\\Controller\\UserController::update()', 'getUserControllerupdateService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.y27w51G.App\\Controller\\AdminController::index()', 'getAdminControllerindexService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.tEL1pRK.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.KHhLDTq.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\TaskController:index' => ['privates', '.service_locator.HTuWMbh.App\\Controller\\TaskController::index()', 'getTaskControllerindexService', true],
            'App\\Controller\\TaskController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\TaskController::new()', 'getTaskControllernewService', true],
            'App\\Controller\\TaskController:show' => ['privates', '.service_locator.kvKRcXA.App\\Controller\\TaskController::show()', 'getTaskControllershowService', true],
            'App\\Controller\\TaskController:edit' => ['privates', '.service_locator.Kt7uJgt.App\\Controller\\TaskController::edit()', 'getTaskControllereditService', true],
            'App\\Controller\\TaskController:delete' => ['privates', '.service_locator.Kt7uJgt.App\\Controller\\TaskController::delete()', 'getTaskControllerdeleteService', true],
            'App\\Controller\\TaskController:toggle' => ['privates', '.service_locator.7Be6WBa.App\\Controller\\TaskController::toggle()', 'getTaskControllertoggleService', true],
            'App\\Controller\\TaskController:list' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TaskController::list()', 'getTaskControllerlistService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.CQIMZqF.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:update' => ['privates', '.service_locator.lQAlGdR.App\\Controller\\UserController::update()', 'getUserControllerupdateService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TaskController::index' => '?',
            'App\\Controller\\TaskController::new' => '?',
            'App\\Controller\\TaskController::show' => '?',
            'App\\Controller\\TaskController::edit' => '?',
            'App\\Controller\\TaskController::delete' => '?',
            'App\\Controller\\TaskController::toggle' => '?',
            'App\\Controller\\TaskController::list' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::update' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TaskController:index' => '?',
            'App\\Controller\\TaskController:new' => '?',
            'App\\Controller\\TaskController:show' => '?',
            'App\\Controller\\TaskController:edit' => '?',
            'App\\Controller\\TaskController:delete' => '?',
            'App\\Controller\\TaskController:toggle' => '?',
            'App\\Controller\\TaskController:list' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:update' => '?',
        ]);
    }
}
