<?php

namespace ContainerXPxOp4A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllerindexService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.HTuWMbh.App\Controller\TaskController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HTuWMbh.App\\Controller\\TaskController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'taskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
        ], [
            'taskRepository' => 'App\\Repository\\TaskRepository',
        ]))->withContext('App\\Controller\\TaskController::index()', $container);
    }
}
