<?php

namespace ContainerXPxOp4A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskFormService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\TaskForm' shared autowired service.
     *
     * @return \App\Form\TaskForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TaskForm.php';

        return $container->privates['App\\Form\\TaskForm'] = new \App\Form\TaskForm();
    }
}
