<?php

namespace ContainerXPxOp4A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProfileFormService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\UserProfileForm' shared autowired service.
     *
     * @return \App\Form\UserProfileForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/UserProfileForm.php';

        return $container->privates['App\\Form\\UserProfileForm'] = new \App\Form\UserProfileForm();
    }
}
