<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXPxOp4A\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXPxOp4A/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXPxOp4A.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXPxOp4A\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerXPxOp4A\App_KernelTestDebugContainer([
    'container.build_hash' => 'XPxOp4A',
    'container.build_id' => '256a8928',
    'container.build_time' => 1750256851,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXPxOp4A');
