<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxkstsp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxkstsp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRxkstsp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRxkstsp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRxkstsp\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rxkstsp',
    'container.build_id' => 'e7b81804',
    'container.build_time' => 1750257509,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxkstsp');
